swagger: '2.0'
info:
  title: Weather MCP Server
  description: Get weather information using MCP server.
  version: 1.0.0
host: <replace with your mcp server url here>
basePath: /
schemes:
  - https
paths:
  /mcp:
    post:
      summary: Weather MCP Server
      x-ms-agentic-protocol: mcp-streamable-1.0
      operationId: InvokeMCP
      responses:
        '200':
          description: Success
securityDefinitions: {}
